import styles from "../../styles/about.module.css";
import { Header } from "@/components/header/header";
import { Curve } from "@/components/pageTransition/curve";
import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function About() {
  return (
    <>
      <Head>
        <title>Nicolas Buisson - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve>
        <div
          className={`${styles.aboutPage} ${geistSans.variable} ${geistMono.variable}`}
        >
          <div className={styles.headerContainer}>
            <Header />
          </div>
          <h2>About page</h2>
          <Link href="/">Home</Link>
          <Link href="/work">Work</Link>
        </div>
      </Curve>
    </>
  );
}
