import { Footer } from "@/components/footer/footer";
import styles from "../styles/home.module.css";
import { HomeHero } from "@/components/homeHero/homeHero";
import { WorkPreview } from "@/components/workPreview/workPreview";
import { Description } from "@/components/description/description";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import { Curve } from "@/components/pageTransition/curve";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Nicolas Buisson</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve>
        <div
          className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
        >
          <HomeHero />
          <section className={styles.aboutSection}>
            <Description />
          </section>
          <WorkPreview />
          <Footer />
        </div>
      </Curve>
    </>
  );
}
