import styles from "../../styles/work.module.css";
import { Header } from "@/components/header/header";
import { Curve } from "@/components/pageTransition/curve";
import { ProjectGallery } from "@/components/projectGallery/projectGallery";
import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Work() {
  return (
    <>
      <Head>
        <title>Nicolas Buisson - Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve>
        <div
          className={`${styles.workPage} ${geistSans.variable} ${geistMono.variable}`}
        >
          <Header />
          <div className={styles.projectGalleryContainer}>
            <ProjectGallery />
          </div>
        </div>
      </Curve>
    </>
  );
}
