import styles from "../../styles/work.module.css";
import { Header } from "@/components/header/header";
import { Curve } from "@/components/pageTransition/curve";
import { Process } from "@/components/process/process";
import { ProjectGallery } from "@/components/projectGallery/projectGallery";
import Head from "next/head";

export default function Work() {
  return (
    <>
      <Head>
        <title>Nicolas Buisson - Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve>
        <div className={styles.workPage}>
          <Header />
          <div className={styles.projectGalleryContainer}>
            <ProjectGallery />
          </div>
          <Process />
          <div style={{ height: "800px" }}></div>
        </div>
      </Curve>
    </>
  );
}
